# my-backendconfig.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hs-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15    
    type: HTTP
    requestPath: /healthz