apiVersion: v1
kind: Service
metadata:
  name: $GKE_APP_NAME 
  namespace: default
  # annotations:
    # # cloud.google.com/backend-config: '{"ports": {"80":"hs-backendconfig"}}'
    # cloud.google.com/neg: '{"ingress": true}'  
spec:
  type: NodePort #LoadBalancer
  selector:
    run: $GKE_APP_NAME
    app: $GKE_APP_NAME
    purpose: $GKE_APP_NAME    
  ports:
  - name: demoapp-http
    port: 8080    
    targetPort: 8080
    protocol: TCP
#  - port: 80
#    targetPort: 8080
