apiVersion: v1
kind: Service
metadata:
  name: $GKE_APP_NAME 
  namespace: default
  annotations: 
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"5000":{}}}' # Creates an NEG after an Ingress is created
    cloud.google.com/backend-config: '{"default": "hs-backendconfig"}'
  # annotations:
    # # cloud.google.com/backend-config: '{"ports": {"80":"hs-backendconfig"}}'
    # cloud.google.com/neg: '{"ingress": true}'  
spec:
  type: NodePort #LoadBalancer
  selector:
    run: $GKE_APP_NAME
    app: $GKE_APP_NAME
    purpose: $GKE_APP_NAME    
  ports:
  - name: demoapp-http
    port: 80    
    targetPort: 8080
    protocol: TCP
#  - port: 80
#    targetPort: 8080
