apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE  
  annotations:
    # cloud.google.com/backend-config: '{"ports": {"80":"hs-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'  
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: $GKE_APP_NAME
    purpose: $GKE_APP_NAME
    run: $GKE_APP_NAME
  ports:
  - port: 80    
    targetPort: 8080
    #protocol: TCP
#  - port: 80
#    targetPort: 8080
